#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
onboarding_source="${EAW_WORKDIR:-}/context_sources/onboarding/eaw"
fixture="$(mktemp -d)"
cleanup() {
  rm -rf -- "$fixture"
  test ! -e "$fixture"
  echo 'teardown: PASS'
}
trap cleanup EXIT
fail() { echo "FAIL: $*" >&2; exit 1; }
mkdir -p "$fixture/config"
for repo in frontend backend database; do
  mkdir -p "$fixture/$repo/docs"
  git init -q "$fixture/$repo"
  printf '%s evidence\n' "$repo" > "$fixture/$repo/docs/source.md"
  printf '%s|%s|target\n' "$repo" "$fixture/$repo" >> "$fixture/config/repos.conf"
done
onboarding_available=false
if [[ -d "$onboarding_source" ]]; then
  mkdir -p "$fixture/context_sources/onboarding"
  for repo in frontend backend database; do
    cp -R "$onboarding_source" "$fixture/context_sources/onboarding/$repo"
  done
  onboarding_available=true
fi
export EAW_WORKDIR="$fixture"
unset EAW_OUT_DIR EAW_CONF EAW_CONFIG_DIR
./scripts/eaw card TEST-BOOTSTRAP --track cross_document_consistency_analysis
source ./scripts/eaw
validate_runtime_workdir
card=TEST-BOOTSTRAP
card_dir="$EAW_OUT_DIR/$card"
eaw_load_card_workflow_context "$card_dir"
# The production materializer binds this log root before invoking run_phase.
OUTDIR="$card_dir"
state="$card_dir/state_card_cross_document_consistency_analysis.yaml"
state_before="$(sha256sum "$state")"
EAW_CARD_WORKFLOW_CURRENT_PHASE=analysis_package
EAW_CARD_WORKFLOW_CURRENT_PHASE_FILE="$ROOT/tracks/cross_document_consistency_analysis/phases/analysis_package.yaml"
EAW_CARD_WORKFLOW_CURRENT_PROMPT_PHASE=analysis_package
EAW_CARD_WORKFLOW_CURRENT_PROMPT_TRACK=cross_document_consistency_analysis
phase_file="$EAW_CARD_WORKFLOW_CURRENT_PHASE_FILE"
package="$card_dir/analysis/70_package_handoff.md"
prompt="$card_dir/prompts/analysis_package.md"
mkdir -p "$card_dir/analysis"
printf 'sources:\n' > "$card_dir/analysis/10_source_manifest.yaml"
for repo in frontend backend database; do
  cat >> "$card_dir/analysis/10_source_manifest.yaml" <<EOF
  - id: $repo
    repository: $repo
    path: docs/source.md
    required: true
    availability: available
EOF
done
check_header() {
  test "$(head -n 1 "$prompt")" = RUNTIME_ENVIRONMENT || fail "$1 missing RUNTIME_ENVIRONMENT header"
  header="$(sed '/^ROLE/,$d' "$prompt")"
  for field in TARGET_DELIVERY_CANDIDATES TARGET_DELIVERY_DECLARED_PATHS ANALYSIS_DELIVERY_PHASE_FILE ANALYSIS_DELIVERY_HELPER AUTHORIZED_INVENTORY_EVIDENCE; do
    grep -q "^$field" <<< "$header" || fail "$1 missing header field $field"
  done
  grep -Fq "ANALYSIS_DELIVERY_PHASE_FILE: $phase_file" <<< "$header"
  grep -Fq "ANALYSIS_DELIVERY_HELPER: $ROOT/scripts/lib/analysis_delivery_contract.sh" <<< "$header"
  for repo in frontend backend database; do
    grep -Fxq "$repo" <<< "$header"
    grep -Fq "$fixture/$repo/docs/source.md" <<< "$header"
  done
  derived="$(eaw_delivery_derive_write_allowlist "$EAW_CONFIG_DIR/repos.conf" "$phase_file" "$card_dir/implementation/00_scope.lock.md" "$card" '' "$package" false)"
  test -z "$derived"
  test "$(sha256sum "$state")" = "$state_before"
}

# Control: the official generator renders without a precreated package.
test ! -e "$package"
if eaw_generate_phase_prompt_artifacts "$card"; then rc=0; else rc=$?; fi
test "$rc" -eq 0 || fail "bootstrap_absent generator exit=$rc"
check_header bootstrap_absent
test ! -d "$card_dir/context/dynamic"
echo 'bootstrap_absent: PASS'

# Real materializer creates the package scaffold before capturing environment.
if eaw_execute_workflow_phase "$card"; then rc=0; else rc=$?; fi
printf 'bootstrap_scaffold materializer exit=%s\n' "$rc"
grep -Fq 'Generated by phase-driven execution' "$package"
check_header bootstrap_scaffold
test "$rc" -eq 0 || fail "bootstrap_scaffold materializer exit=$rc"
echo 'bootstrap_scaffold: PASS'

printf 'ANALYSIS_STATUS: INCOMPLETE\nPERSISTENCE_STATUS: BLOCKED\n' > "$package"
if eaw_generate_phase_prompt_artifacts "$card"; then rc=0; else rc=$?; fi
test "$rc" -eq 0 || fail "bootstrap_blocked generator exit=$rc"
check_header bootstrap_blocked
echo 'bootstrap_blocked: PASS'

# Existing dynamic context is produced by its official materializer.
eaw_dynamic_context_materialize "$card_dir"
dynamic_before="$(find "$card_dir/context/dynamic" -type f -print0 | sort -z | xargs -0 sha256sum)"
if [[ "$onboarding_available" == true ]]; then
  onboarding_before="$(find "$fixture/context_sources/onboarding" -type f -print0 | sort -z | xargs -0 sha256sum)"
fi
if eaw_generate_phase_prompt_artifacts "$card"; then rc=0; else rc=$?; fi
test "$rc" -eq 0 || fail "context_guardrail generator exit=$rc"
test "$(find "$card_dir/context/dynamic" -type f -print0 | sort -z | xargs -0 sha256sum)" = "$dynamic_before"
test ! -d "$card_dir/context/onboarding"
check_header context_guardrail
if [[ "$onboarding_available" == true ]]; then
  test "$(find "$fixture/context_sources/onboarding" -type f -print0 | sort -z | xargs -0 sha256sum)" = "$onboarding_before"
  template="$(load_prompt "$EAW_CARD_WORKFLOW_CURRENT_PROMPT_TRACK" "$EAW_CARD_WORKFLOW_CURRENT_PROMPT_PHASE" "$card" "$EAW_OUT_DIR")"
  if grep -q 'context_sources/onboarding' "$template"; then
    grep -Eq "$fixture/context_sources/onboarding/(frontend|backend|database)/" "$prompt"
  else
    echo 'context_guardrail onboarding_reference: NO-OP (active analysis_package template declares no onboarding reference)'
  fi
fi
echo "context_guardrail: PASS (official dynamic bytes and workspace onboarding bytes preserved; onboarding_available=$onboarding_available)"

# Injections exist only in subshell memory; the functions under test are real.
prompt_before="$(sha256sum "$prompt")"
for operation in generator executor runner; do
  if (
    eaw_runtime_environment_block() { echo 'injected environment failure' >&2; return 23; }
    case "$operation" in
      generator) eaw_generate_phase_prompt_artifacts "$card" ;;
      executor) eaw_execute_workflow_phase "$card" ;;
      runner) run_phase workflow_phase_analysis_package true eaw_execute_workflow_phase "$card" ;;
    esac
  ) > "$fixture/$operation.log" 2>&1; then rc=0; else rc=$?; fi
  cat "$fixture/$operation.log"
  printf 'failure_propagation %s: exit=%s\n' "$operation" "$rc"
  test "$rc" -eq 23 || fail "$operation did not propagate 23"
  if grep -Eq 'wrote_prompt=|action=phase_driven_execution|workflow_phase_analysis_package -> OK' "$fixture/$operation.log"; then fail "$operation declared success"; fi
  test "$(sha256sum "$prompt")" = "$prompt_before"
done
grep -q 'workflow_phase_analysis_package -> FAIL' "$fixture/runner.log"
test -s "$card_dir/execution.log"
grep -q 'workflow_phase_analysis_package|FAIL|' "$card_dir/execution.log"
if grep -q 'workflow_phase_analysis_package|OK|' "$card_dir/execution.log"; then fail 'runner log declared OK'; fi
test "$(sha256sum "$state")" = "$state_before"
echo 'failure_propagation: PASS'

# An earlier alias must fail before any later alias can mask its return.
if (
  eaw_yaml_phase_output_prompts() { printf 'first\nsecond\n'; }
  eaw_render_phase_prompt_template() {
    if [[ "$3" == FIRST ]]; then echo 'injected first renderer failure' >&2; return 29; fi
    echo 'later_alias_called'
    return 0
  }
  eaw_generate_phase_prompt_artifacts "$card"
) > "$fixture/renderer.log" 2>&1; then rc=0; else rc=$?; fi
cat "$fixture/renderer.log"
printf 'renderer_failure: exit=%s\n' "$rc"
test "$rc" -eq 29 || fail 'renderer return was masked'
if grep -Eq 'later_alias_called|wrote_prompt=|action=phase_driven_execution' "$fixture/renderer.log"; then fail 'renderer failure continued to success'; fi
test "$(sha256sum "$prompt")" = "$prompt_before"
echo 'renderer_failure: PASS'
echo 'analysis_delivery_bootstrap_smoke: PASS (materialization coverage; full analytical lifecycle not certified)'
