#!/usr/bin/env bash

eaw_phase_completion_strategy_name() {
	local file="$1"
	awk '
		function trim(s) {
			sub(/^[[:space:]]+/, "", s)
			sub(/[[:space:]]+$/, "", s)
			sub(/^"/, "", s)
			sub(/"$/, "", s)
			return s
		}
		/^phase:[[:space:]]*$/ { in_phase=1; next }
		in_phase && /^[^[:space:]]/ { in_phase=0; in_completion=0 }
		in_phase && /^  completion:[[:space:]]*$/ { in_completion=1; next }
		in_completion && /^  [^[:space:]]/ { in_completion=0 }
		in_completion && /^    strategy:[[:space:]]*/ {
			line=$0
			sub(/^    strategy:[[:space:]]*/, "", line)
			print trim(line)
			exit
		}
	' "$file"
}

eaw_phase_completion_required_artifacts() {
	local file="$1"
	awk '
		/^phase:[[:space:]]*$/ { in_phase=1; next }
		in_phase && /^[^[:space:]]/ { in_phase=0; in_completion=0; in_required=0 }
		in_phase && /^  completion:[[:space:]]*$/ { in_completion=1; next }
		in_completion && /^  [^[:space:]]/ { in_completion=0; in_required=0 }
		in_completion && /^    required_artifacts:[[:space:]]*$/ { in_required=1; next }
		in_required && /^    [^[:space:]-]/ { in_required=0 }
		in_required && /^      - / {
			line=$0
			sub(/^      - /, "", line)
			print line
		}
	' "$file"
}

eaw_phase_completion_evaluate_required_artifacts_exist() {
	local card="$1"
	local card_dir="$2"
	local phase_id="$3"
	local phase_file="$4"
	local rel_path
	local -a missing_artifacts=()

	while IFS= read -r rel_path; do
		[[ -n "$rel_path" ]] || continue
		if [[ ! -e "$card_dir/$rel_path" ]]; then
			missing_artifacts+=("$rel_path")
		fi
	done < <(eaw_phase_completion_required_artifacts "$phase_file")

	if [[ ${#missing_artifacts[@]} -gt 0 ]]; then
		printf "ERROR: card %s phase '%s' is incomplete; missing required artifacts:" "$card" "$phase_id" >&2
		printf " %s" "${missing_artifacts[@]}" >&2
		printf "\n" >&2
		return 1
	fi

	return 0
}

eaw_phase_completion_detect_card_template_type() {
	local card="$1"
	local card_dir="$2"

	if [[ -f "$card_dir/bug_${card}.md" ]]; then
		printf "bug\n"
	elif [[ -f "$card_dir/spike_${card}.md" ]]; then
		printf "spike\n"
	elif compgen -G "$card_dir/state_card_repo_onboarding.yaml" > /dev/null 2>&1; then
		printf "repo_onboarding\n"
	else
		printf "feature\n"
	fi
}

eaw_phase_completion_render_expected_scaffold() {
	local card="$1"
	local card_dir="$2"
	local phase_id="$3"
	local rel_path="$4"
	local type template_file

	case "$rel_path" in
	investigations/00_intake.md)
		type="$(eaw_phase_completion_detect_card_template_type "$card" "$card_dir")"
		template_file="$EAW_TEMPLATES_DIR/intake_${type}.md"
		sed "s/<CARD>/${card}/g" "$template_file"
		;;
	investigations/20_findings.md)
		sed "s/<CARD>/${card}/g" "$EAW_TEMPLATES_DIR/20_findings.md"
		;;
	investigations/30_hypotheses.md)
		sed "s/<CARD>/${card}/g" "$EAW_TEMPLATES_DIR/30_hypotheses.md"
		;;
	investigations/40_next_steps.md)
		sed "s/<CARD>/${card}/g" "$EAW_TEMPLATES_DIR/40_next_steps.md"
		;;
	implementation/00_scope.lock.md)
		cat <<EOF
# Scope Lock - Card $card

## In Scope

## Out of Scope
EOF
		;;
	implementation/10_change_plan.md)
		cat <<EOF
# Change Plan - Card $card

## Steps

## Validation
EOF
		;;
	implementation/20_patch_notes.md)
		cat <<EOF
# Patch Notes - Card $card

## Changes

## Risks
EOF
		;;
	*)
		cat <<EOF
# ${phase_id} artifact

Generated by phase-driven execution for card $card.
EOF
		;;
	esac
}

eaw_phase_completion_render_source_scaffold() {
	local card="$1"
	local card_dir="$2"
	local phase_id="$3"
	local rel_path="$4"
	local type template_file

	case "$rel_path" in
	investigations/00_intake.md)
		type="$(eaw_phase_completion_detect_card_template_type "$card" "$card_dir")"
		template_file="$EAW_TEMPLATES_DIR/intake_${type}.md"
		cat "$template_file"
		;;
	investigations/20_findings.md)
		cat "$EAW_TEMPLATES_DIR/20_findings.md"
		;;
	investigations/30_hypotheses.md)
		cat "$EAW_TEMPLATES_DIR/30_hypotheses.md"
		;;
	investigations/40_next_steps.md)
		cat "$EAW_TEMPLATES_DIR/40_next_steps.md"
		;;
	*)
		eaw_phase_completion_render_expected_scaffold "$card" "$card_dir" "$phase_id" "$rel_path"
		;;
	esac
}

eaw_phase_completion_artifact_has_meaningful_content() {
	local card="$1"
	local card_dir="$2"
	local phase_id="$3"
	local rel_path="$4"
	local file="$card_dir/$rel_path"
	local scaffold_file
	local source_scaffold_file

	if [[ ! -s "$file" ]]; then
		return 1
	fi

	scaffold_file="$(mktemp)"
	eaw_phase_completion_render_expected_scaffold "$card" "$card_dir" "$phase_id" "$rel_path" >"$scaffold_file"
	if cmp -s "$file" "$scaffold_file"; then
		rm -f "$scaffold_file"
		return 1
	fi

	source_scaffold_file="$(mktemp)"
	eaw_phase_completion_render_source_scaffold "$card" "$card_dir" "$phase_id" "$rel_path" >"$source_scaffold_file"
	if cmp -s "$file" "$source_scaffold_file"; then
		rm -f "$scaffold_file" "$source_scaffold_file"
		return 1
	fi
	rm -f "$scaffold_file" "$source_scaffold_file"
	return 0
}

eaw_phase_completion_evaluate_required_artifacts_filled() {
	local card="$1"
	local card_dir="$2"
	local phase_id="$3"
	local phase_file="$4"
	local rel_path
	local -a unfilled_artifacts=()

	if ! eaw_phase_completion_evaluate_required_artifacts_exist "$card" "$card_dir" "$phase_id" "$phase_file"; then
		return 1
	fi

	while IFS= read -r rel_path; do
		[[ -n "$rel_path" ]] || continue
		if ! eaw_phase_completion_artifact_has_meaningful_content "$card" "$card_dir" "$phase_id" "$rel_path"; then
			unfilled_artifacts+=("$rel_path")
		fi
	done < <(eaw_phase_completion_required_artifacts "$phase_file")

	if [[ ${#unfilled_artifacts[@]} -gt 0 ]]; then
		printf "ERROR: card %s phase '%s' is incomplete; unfilled required artifacts:" "$card" "$phase_id" >&2
		printf " %s" "${unfilled_artifacts[@]}" >&2
		printf "\n" >&2
		return 1
	fi

	return 0
}

eaw_phase_completion_evaluate() {
	local card="$1"
	local card_dir="$2"
	local phase_id="$3"
	local phase_file="$4"
	local strategy

	strategy="$(eaw_phase_completion_strategy_name "$phase_file")"
	case "$strategy" in
	"" | required_artifacts_exist)
		eaw_phase_completion_evaluate_required_artifacts_exist "$card" "$card_dir" "$phase_id" "$phase_file"
		;;
	*)
		echo "ERROR: card ${card} phase '${phase_id}' uses unsupported completion strategy '${strategy}'" >&2
		return 1
		;;
	esac
}

eaw_phase_completion_evaluate_strict() {
	local card="$1"
	local card_dir="$2"
	local phase_id="$3"
	local phase_file="$4"
	local strategy

	strategy="$(eaw_phase_completion_strategy_name "$phase_file")"
	case "$strategy" in
	"" | required_artifacts_exist)
		eaw_phase_completion_evaluate_required_artifacts_filled "$card" "$card_dir" "$phase_id" "$phase_file"
		;;
	*)
		eaw_phase_completion_evaluate "$card" "$card_dir" "$phase_id" "$phase_file"
		;;
	esac
}

eaw_card_requires_mandatory_analysis_audit() {
	local card_dir="$1"
	local raw_card_explication="$card_dir/ingest/raw_card_explication.md"

	[[ -f "$raw_card_explication" ]] || return 1
	grep -Fq 'analysis/00_track_audit.md' "$raw_card_explication" || return 1
	grep -Fq 'analysis/10_issues_detected.md' "$raw_card_explication" || return 1
	grep -Fq 'analysis/20_refactor_plan.md' "$raw_card_explication" || return 1
	return 0
}

eaw_card_enforce_mandatory_analysis_audit() {
	local card="$1"
	local card_dir="$2"
	local phase_id="$3"
	local rel_path
	local -a missing_artifacts=()

	case "$phase_id" in
	implementation_planning | implementation_executor)
		;;
	*)
		return 0
		;;
	esac

	if ! eaw_card_requires_mandatory_analysis_audit "$card_dir"; then
		return 0
	fi

	for rel_path in \
		analysis/00_track_audit.md \
		analysis/10_issues_detected.md \
		analysis/20_refactor_plan.md; do
		if [[ ! -s "$card_dir/$rel_path" ]]; then
			missing_artifacts+=("$rel_path")
		fi
	done

	if [[ ${#missing_artifacts[@]} -gt 0 ]]; then
		printf "ERROR: card %s phase '%s' blocked; auditoria mandatoria ausente; execucao corretiva bloqueada por contrato:" "$card" "$phase_id" >&2
		printf " %s" "${missing_artifacts[@]}" >&2
		printf "\n" >&2
		return 1
	fi

	return 0
}
