#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$ROOT_DIR/config"
LOCAL_CONF="$CONFIG_DIR/repos.local.conf"
TARGET_CONF="$CONFIG_DIR/repos.conf"
EXAMPLE_CONF="$CONFIG_DIR/repos.example.conf"

mkdir -p "$CONFIG_DIR"

if [[ -f "$LOCAL_CONF" ]]; then
	cp "$LOCAL_CONF" "$TARGET_CONF"
	echo "Using local config: $LOCAL_CONF -> $TARGET_CONF"
	exit 0
fi

{
	echo "# Auto-generated repos.conf"
	echo "# Format: key|path"
	echo "# Generated by scripts/sync-repos-config.sh"
} >"$TARGET_CONF"

added=0

if [[ -n "${FW_PREFIX:-}" ]]; then
	echo "framework|$FW_PREFIX" >>"$TARGET_CONF"
	added=1
fi

if [[ -n "${BEFW_HOME:-}" ]]; then
	echo "framework-backend|$BEFW_HOME" >>"$TARGET_CONF"
	added=1
fi

if [[ -n "${BE_HOME:-}" ]]; then
	echo "backend|$BE_HOME" >>"$TARGET_CONF"
	added=1
fi

if [[ -n "${TS_PREFIX:-}" ]]; then
	echo "frontend|$TS_PREFIX" >>"$TARGET_CONF"
	added=1
fi

if [[ "$added" -eq 0 ]]; then
	cp "$EXAMPLE_CONF" "$TARGET_CONF"
	echo "No env vars found; using fallback: $EXAMPLE_CONF -> $TARGET_CONF"
else
	echo "Generated $TARGET_CONF from environment variables"
fi

exit 0
